name: PasswordWhitelist
version: $version
api-version: $mcVersion

folia-supported: true

main: net.strokkur.passwordwhitelist.PasswordWhitelist
bootstrapper: net.strokkur.passwordwhitelist.PasswordWhitelistBootstrap
loader: net.strokkur.passwordwhitelist.PasswordWhitelistLoader

permissions:
  passwordwhitelist.command.use:
    description: Main permission required to run the /passwordwhitelist command
    default: op
  
  passwordwhitelist.command.help:
    description: Permission required to run the '/passwordwhitelist help' subcommand
    default: true