name: 'PasswordWhitelist: Build'

on:
  push:
    branches: [ "main", "dev*" ]
  pull_request:
    branches: [ "main", "dev*" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execution rights to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
        
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*
          if-no-files-found: error
          compression-level: 0       